
name: 1python run main.py 

on:
  schedule:
    - cron: '0 8 * * 2'

env:
  MEMBER: ${{ secrets.mid }}

jobs:
  qndxx:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up env
        run: pip install requests~=2.28.1
          
      - name: Run main command
        run: python main.py
